/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WrappedRouteImport } from './routes/wrapped'
import { Route as StreakLegacyRouteImport } from './routes/streak-legacy'
import { Route as SquadRouteImport } from './routes/squad'
import { Route as SpendDnaRouteImport } from './routes/spend-dna'
import { Route as RoastRouteImport } from './routes/roast'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as CityPulseRouteImport } from './routes/city-pulse'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as AppRouteImport } from './routes/app'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as IndexRouteImport } from './routes/index'

const WrappedRoute = WrappedRouteImport.update({
  id: '/wrapped',
  path: '/wrapped',
  getParentRoute: () => rootRouteImport,
} as any)
const StreakLegacyRoute = StreakLegacyRouteImport.update({
  id: '/streak-legacy',
  path: '/streak-legacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SquadRoute = SquadRouteImport.update({
  id: '/squad',
  path: '/squad',
  getParentRoute: () => rootRouteImport,
} as any)
const SpendDnaRoute = SpendDnaRouteImport.update({
  id: '/spend-dna',
  path: '/spend-dna',
  getParentRoute: () => rootRouteImport,
} as any)
const RoastRoute = RoastRouteImport.update({
  id: '/roast',
  path: '/roast',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const CityPulseRoute = CityPulseRouteImport.update({
  id: '/city-pulse',
  path: '/city-pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/app': typeof AppRoute
  '/challenges': typeof ChallengesRoute
  '/city-pulse': typeof CityPulseRoute
  '/coach': typeof CoachRoute
  '/goals': typeof GoalsRoute
  '/roast': typeof RoastRoute
  '/spend-dna': typeof SpendDnaRoute
  '/squad': typeof SquadRoute
  '/streak-legacy': typeof StreakLegacyRoute
  '/wrapped': typeof WrappedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/app': typeof AppRoute
  '/challenges': typeof ChallengesRoute
  '/city-pulse': typeof CityPulseRoute
  '/coach': typeof CoachRoute
  '/goals': typeof GoalsRoute
  '/roast': typeof RoastRoute
  '/spend-dna': typeof SpendDnaRoute
  '/squad': typeof SquadRoute
  '/streak-legacy': typeof StreakLegacyRoute
  '/wrapped': typeof WrappedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/app': typeof AppRoute
  '/challenges': typeof ChallengesRoute
  '/city-pulse': typeof CityPulseRoute
  '/coach': typeof CoachRoute
  '/goals': typeof GoalsRoute
  '/roast': typeof RoastRoute
  '/spend-dna': typeof SpendDnaRoute
  '/squad': typeof SquadRoute
  '/streak-legacy': typeof StreakLegacyRoute
  '/wrapped': typeof WrappedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/app'
    | '/challenges'
    | '/city-pulse'
    | '/coach'
    | '/goals'
    | '/roast'
    | '/spend-dna'
    | '/squad'
    | '/streak-legacy'
    | '/wrapped'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/app'
    | '/challenges'
    | '/city-pulse'
    | '/coach'
    | '/goals'
    | '/roast'
    | '/spend-dna'
    | '/squad'
    | '/streak-legacy'
    | '/wrapped'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/app'
    | '/challenges'
    | '/city-pulse'
    | '/coach'
    | '/goals'
    | '/roast'
    | '/spend-dna'
    | '/squad'
    | '/streak-legacy'
    | '/wrapped'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  AppRoute: typeof AppRoute
  ChallengesRoute: typeof ChallengesRoute
  CityPulseRoute: typeof CityPulseRoute
  CoachRoute: typeof CoachRoute
  GoalsRoute: typeof GoalsRoute
  RoastRoute: typeof RoastRoute
  SpendDnaRoute: typeof SpendDnaRoute
  SquadRoute: typeof SquadRoute
  StreakLegacyRoute: typeof StreakLegacyRoute
  WrappedRoute: typeof WrappedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wrapped': {
      id: '/wrapped'
      path: '/wrapped'
      fullPath: '/wrapped'
      preLoaderRoute: typeof WrappedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streak-legacy': {
      id: '/streak-legacy'
      path: '/streak-legacy'
      fullPath: '/streak-legacy'
      preLoaderRoute: typeof StreakLegacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squad': {
      id: '/squad'
      path: '/squad'
      fullPath: '/squad'
      preLoaderRoute: typeof SquadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spend-dna': {
      id: '/spend-dna'
      path: '/spend-dna'
      fullPath: '/spend-dna'
      preLoaderRoute: typeof SpendDnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roast': {
      id: '/roast'
      path: '/roast'
      fullPath: '/roast'
      preLoaderRoute: typeof RoastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city-pulse': {
      id: '/city-pulse'
      path: '/city-pulse'
      fullPath: '/city-pulse'
      preLoaderRoute: typeof CityPulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  AppRoute: AppRoute,
  ChallengesRoute: ChallengesRoute,
  CityPulseRoute: CityPulseRoute,
  CoachRoute: CoachRoute,
  GoalsRoute: GoalsRoute,
  RoastRoute: RoastRoute,
  SpendDnaRoute: SpendDnaRoute,
  SquadRoute: SquadRoute,
  StreakLegacyRoute: StreakLegacyRoute,
  WrappedRoute: WrappedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
